### ISSUE TITLE
NOOBS

### ISSUE THREAD

**Issue by Benjaminsson** [lukaskubis/raspbian-jesse-kiosk#1]
Can you follow this guide with NOOBS or is this only doable with Jessie?

**Comment by lukaskubis** [comment]
I've never used NOOBS, but from what I've read [here](https://www.raspberrypi.org/documentation/installation/noobs.md), NOOBS in only an OS installation manager. So if you use NOOBS to install the latest raspbian (if it's included, which it should be), it should work just fine.

**Comment by Benjaminsson** [comment]
Yes! You're right! And it worked! Thanks!
